language: java
jdk:
  - oraclejdk8
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: false
